### ISSUE TITLE
Missing illustrations

### ISSUE THREAD

**Issue by kyranb** [KaiWedekind/vue-undraw#3]
First of all, thanks for making this :)

I noticed some illustrations are missing. Did you manually add each svg manually or is there a way to scrape the site and update this repository with new additions?

**Comment by KaiWedekind** [comment]
Hi kyranb, thanks for pointing that out. Could you give us some names of the illustrations that are missing? Illustrations are downloaded manually but creating the components is fully automated. Are you using version 2.0.4? Thanks

**Comment by kyranb** [comment]
Thanks Kai. 

I came across this API mirror which might be useful to automatically download all the missing ones and then generate the components.

 https://undraw.oswaldlabs.com/

i.e: https://undraw.oswaldlabs.com/hex-code/podcast-audience.svg

**Comment by KaiWedekind** [comment]
Just checked the https://undraw.oswaldlabs.com page. It doesn't have all illustrations. It only holds a list with 439 illustrations but undraw has 530 illustrations already.

**Comment by KaiWedekind** [comment]
Closing this, oswaldlabs API is not complete. Creating my own list to automatically download the illustrations. Vue-Undraw 2.0.6 should have all illustrations.
